version: '3.8'
services:
  api:
    image: evertonst/express-api:v1.0.0
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    restart: unless-stopped


  mongo:
    image: mongo:4.4
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongo', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}
